version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: carwash_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - carwash_network

  backend:
    build: ./backend
    container_name: carwash_backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - carwash_network

  frontend:
    build: ./frontend
    container_name: carwash_frontend
    restart: always
    env_file:
      - .env
    networks:
      - carwash_network

  nginx:
    build: ./nginx
    container_name: carwash_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - carwash_network

  certbot:
    image: certbot/certbot:latest
    container_name: carwash_certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - nginx

networks:
  carwash_network:
    driver: bridge

volumes:
  postgres_data:
