{
 "title": "Carwash Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Все логи",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"carwash_backend\"}"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"carwash_backend\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "Количество логов по уровням",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"carwash_backend\", level=\"error\"}[5m]))",
     "legendFormat": "Ошибки"
    },
    {
     "expr": "sum(count_over_time({job=\"carwash_backend\", level=\"info\"}[5m]))",
     "legendFormat": "Информация"
    }
   ]
  },
  {
   "title": "Входящие запросы",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"carwash_backend\"} |= \"Incoming request\""
    }
   ]
  },
  {
   "title": "Исходящие ответы",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"carwash_backend\"} |= \"Outgoing response\""
    }
   ]
  }
 ]
}