DROP TABLE IF EXISTS link_tokens;
ALTER TABLE sessions DROP COLUMN IF EXISTS source;
ALTER TABLE users DROP COLUMN IF EXISTS phone_verified_at;
ALTER TABLE users DROP COLUMN IF EXISTS phone;
ALTER TABLE users ALTER COLUMN telegram_id SET NOT NULL;
