auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: loki
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Оптимизированные настройки хранения - 1 день
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  max_cache_freshness_per_query: 5m
  split_queries_by_interval: 30m
  max_query_parallelism: 16
  max_streams_per_user: 0
  max_line_size: 128000
  max_entries_limit_per_query: 2000
  max_query_series: 200
  max_query_lookback: 0s
  max_query_length: 24h
  cardinality_limit: 50000
  max_streams_matchers_per_query: 500
  max_concurrent_tail_requests: 5
  max_queriers_per_tenant: 0
  ruler_max_rules_per_rule_group: 0
  ruler_max_rule_groups_per_tenant: 0
  # Увеличиваем лимиты для предотвращения 429 ошибок
  per_stream_rate_limit: 8MB
  per_stream_rate_limit_burst: 32MB
  max_global_streams_per_user: 0
  max_chunks_per_query: 1000000
  # 1 день хранения для экономии ресурсов
  retention_period: 24h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 30m
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 50

analytics:
  reporting_enabled: false