global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - системные метрики
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /metrics

  # Backend Go приложение - кастомные метрики
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Nginx - метрики веб-сервера
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Grafana - метрики самого Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Loki - метрики системы логов
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Promtail - метрики агента сбора логов
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    scrape_interval: 30s
    metrics_path: /metrics

# Настройки хранения (указываются в командной строке)

# Настройки алертов
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
